In [1]:
import numpy as np

#BASICS

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
b = np.array([[1,2,3],[4,6,8]])
print(b)

[[1 2 3]
 [4 6 8]]


In [4]:
#get dimension
b.ndim

2

In [5]:
#get shape
print(a.shape)
print(b.shape)

(4,)
(2, 3)


In [6]:
#get types
print(b.dtype)

c = np.array([1,2], dtype = "int8")
print(c)
c.dtype

int64
[1 2]


dtype('int8')

In [7]:
d = np.array([[1,2],[2,3,4]], dtype = "object")
print(d)
print(d.ndim)

[list([1, 2]) list([2, 3, 4])]
1


In [8]:
#get size (in bytes) of one element
print(a.itemsize)
print(c.itemsize)

8
1


In [9]:
# get full size
print(c.nbytes)

2


#Accessing/Changing specific elements,rows,columns,etc.


In [10]:
ar = np.array([[1,2,3,4,5],[0,6,7,8,9]])
print(ar)

[[1 2 3 4 5]
 [0 6 7 8 9]]


In [11]:
#get specific element
print(ar[0])
print(ar[1,2])
print(ar[:,2])
print(ar[1,2:4])

[1 2 3 4 5]
7
[3 7]
[7 8]


In [12]:
# from start index end index and step size
print(ar[0, 1:5:2])

[2 4]


In [13]:
# change something
ar[0,1] = 20
print(ar)

[[ 1 20  3  4  5]
 [ 0  6  7  8  9]]


In [14]:
ar[:,2] = [77,66]
print(ar)

[[ 1 20 77  4  5]
 [ 0  6 66  8  9]]


#INITIALIZE DIFFERENT TYPES OF ARRAYS

In [15]:
  #  All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# All 1s matrix
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones((2,3),dtype="int8")

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [19]:
# Any other number
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [20]:
np.full(ar.shape,4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [21]:
# random decimal numbers
np.random.rand(4,2)

array([[0.21199637, 0.94565933],
       [0.2868185 , 0.11068578],
       [0.88955683, 0.1796575 ],
       [0.45414262, 0.39045087]])

In [22]:
# random integer values
np.random.randint(5,size=(2,3))

array([[3, 3, 1],
       [0, 1, 2]])

In [23]:
# the identity matrix
np.identity(3,dtype="int8")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [24]:
# repeatation of array in 1d and 2d
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [25]:
arr2 = np.array([[1,2,3]])
r2 = np.repeat(arr2,2,axis=0)
print(r2)

[[1 2 3]
 [1 2 3]]


In [26]:
# example to practice
out = np.ones((5,5))
print(out,end='\n\n')

z = np.zeros((3,3))
z[1,1] = 9
print(z,end="\n\n")

out[1:4,1:4] = z
print(out)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
# be
# carefull
# copying arrays

arr1 = np.array([1,2,3])
b = a.copy()
# b = a don't work ,it only create the refrence variable for a
print(b)
a[0] = 44
print(b)

[1 2 3 4]
[1 2 3 4]


#MATHEMATICS

In [28]:
math1 = np.array([1,2,3])

In [29]:
print(math1-3)
print(math1/2)
print(math1*3)
print(math1**3)

[-2 -1  0]
[0.5 1.  1.5]
[3 6 9]
[ 1  8 27]


In [30]:
math2 = np.array([4,5,6,])
print(math1+math2)

[5 7 9]


In [31]:
# take sign of all value
print(np.sin(math1))
print(np.cos(0))

[0.84147098 0.90929743 0.14112001]
1.0


#LINEAR ALGEBRA

In [32]:
la1 = np.ones((2,3))
print(la1)

la2 = np.full((3,2),2)
print(la2)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [33]:
print(np.matmul(la1,la2))

[[6. 6.]
 [6. 6.]]


In [34]:
la3 = np.identity(3)
np.linalg.det(la3)

1.0

In [35]:
# we can use matrix functions like
# normalisation
# equivvalence
# inverse
# trace
# etc

#STATISTICS

In [36]:
stats = np.array([[1,2,3],[4,5,6],[0,9,8]])
print(stats)

[[1 2 3]
 [4 5 6]
 [0 9 8]]


In [37]:
print(np.min(stats))
# for minimum in every row
print(np.min(stats,axis=1))
# for minimum in every col
print(np.min(stats,axis=0))


0
[1 4 0]
[0 2 3]


In [38]:
# max function also
np.max(stats)

9

#REORGANIZING ARRAYS

In [48]:
ra1 = np.array([[1,2,3,4],[5,6,7,8]])
print(ra1)
#  reshape(no.of list,row,col)
ra2 = ra1.reshape((2,4,1)) 
print(ra2)

[[1 2 3 4]
 [5 6 7 8]]
[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]]


In [52]:
# verticle stacking
v1 = np.array([1,2,3,4])
v2 = np.array([9,8,7,6])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [53]:
# horizontal stack
h1 = np.array([[1,2],[4,5]])
h2 = np.array([[7,6],[5,3]])

np.hstack((h1,h2))

array([[1, 2, 7, 6],
       [4, 5, 5, 3]])

#Miscellaneos

In [60]:
# load data from file
filedata = np.genfromtxt('/data.txt',delimiter=',')

In [62]:
# changing type of data
filedata.astype("int16")

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int16)

In [63]:
# ADVANCE INDEXING AND BOOLEAN MASKING

filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [64]:
filedata[filedata>50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [65]:
# index with a list in numpy
m = np.array([1,2,3,4,5,6,7,8,9,])         
m[[4,0,5]]

array([5, 1, 6])

In [66]:
np.any(filedata>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])